package(default_visibility = ['//visibility:public'])

cc_binary(
  name = 'frc1678',
  srcs = [
    'citrus_robot.cpp',
  ],
  deps = [
    '@wpilib//:main',
    '@eigen//:main',
    '//frc1678/claw'
  ],
)
